# Hello_world 範例程式 - 推論 {#chap-hello-world-inference}

本章節對應到 [TinyML TensorFLow Lite 機器學習中文版](https://www.books.com.tw/products/0010865580) 的第六章. (原書第五章是說明 hello_world 原始程式及測試碼, 可以當作後續的研究分析, 列入 §附錄 \@ref(appendixb) 的主題)

上一章, 我們已經建立了可以轉移到開發板上執行的模型, 模型只是機器學習應用 app 的一部分而已, TFLM 提供不同開發板的 hello_world app, 需要在筆電上將模型加入原始程式, 重新編譯成不同開發板可以執行的程式碼(不同 CPU 的程式碼無法跨平台執行), 也可以在 PC 或 Mac 上模擬結果. 

本文介紹可以運作 hello_world 示範程式的有以下的前兩種 (網路上有更新, 可以支援更多設備):  

* [Arduino Nano 33 BLE Sense](#arduino-nano33-hello-world)  
* [ST Microelectronics STM32F746NG Discovery kit](#disco-f746ng-hello-world)  
* SparkFun Edge ([TinyML TensorFLow Lite 機器學習中文版](https://www.books.com.tw/products/0010865580) 書上有介紹, 但手上沒有這塊開發板, 就不介紹了)   
* 2021/4/6 新增實驗 [ESP32-CAM](#esp32-cam-hello-world)

<a id="disco_f746ng_hello_world"></a>  

## 在 STM32 DISCO_F746NG 上實現 hello_world {#disco-f746ng-hello-world}
### (無痛執行)在筆電上編譯程式, 並下載至 STM32 DISCO_F746NG

因為 TensorFlow Lite Micro 的開發持續在進行, 部份文件並沒有隨著開發進度而更新, 如果照著 github 上執行會產生一些錯誤, 而且, 在編譯 (make) 之前, 需要將 STM32 DISCO_F746NG 相關檔案複製到主程式目錄下, 因此, 我在 github 創建了一個 branch, 針對 DISCO_F746NG 的開發板做了檔案安排及設定調整, 可以直接編譯, 並下載到 DISCO_F746NG 開發板上執行. 

參考[我的 TFLM github - hello_world](https://github.com/marconi1964/tensorflow/blob/example/tensorflow/lite/micro/examples/hello_world/disco_f746ng/README_disco_f746ng.md)無痛執行

在下一節說明如果從 TFLM github 官網下載內容時, 需要做的修改.

### (微痛執行)在筆電上編譯程式, 並下載至 STM32 DISCO_F746NG
此節乃針對已經熟悉上一節的內容, 順利執行後, 進一步從 TFLM github 官網下載, 得自行修改部份內容方能順利執行無誤.

**動手修改內容**

需要修改的內容有  
1. 改從 https://github.com/tensorflow 官網下載  
2. 將 tensorflow/lite/micro/examples/hello_world/disco_f746ng/ 這目錄改名成為 tensorflow/lite/micro/examples/hello_world/mbed/   
其餘從 make 以後的操作維持跟原先內容不變

#### 改從 https://github.com/tensorflow 官網下載

```
# 從我的 github
$ git clone -b example --depth 1 https://github.com/marconi1964/tensorflow.git
# 改到用 Tensorflow 官網的 github
$ git clone --depth 1 https://github.com/marconi1964/tensorflow.git
# 或是
$ git clone --depth 1 https://github.com/tensorflow/tensorflow.git
$ cd tensorflow
```

#### 將 tensorflow/lite/micro/examples/hello_world/disco_f746ng/ 這目錄改名成為 tensorflow/lite/micro/examples/hello_world/mbed/

DISCO_F746NG 的驅動程式 (constant.cc 與 output_handler.cc) 跟標準的示範程式不同, 需要讓 make 把 F746NG 的驅動程式包含在主程式才能在開發板上執行, 這部分已經在 Makefile 完成, 只是目前 Makefile 的寫法是擷取 TARGET=mbed 中的 'mbed', 再到 hello_world 目錄下尋找 'mbed' 子目錄 (這部分的程式設定有問題, 已經在 TensorFlow github 上發 issue), 而 mbed 子目錄是不存在, 且 Makefile 不會去尋找 disco_f746ng 子目錄.


```
# 接續上一個動作, 已經在 tensorflow 目錄下, 切換到 hello_world 示範程式目錄
$ cd tensorflow/lite/micro/examples/hello_world/

$ mv disco_f746ng mbed
# 完成後, 回到 tensorflow 主目錄下
$ cd ~/tensorflow
```

(以上的動作, 看起來很簡單, 卻是我花最多時間的地方, 需要去了解 Makefile 及層層疊加上的 Makefile.inc 和 *_makefile.inc 的複雜架構.)  


繼續執行 make 以及後續的動作

```
$ make -f tensorflow/lite/micro/tools/make/Makefile TARGET=mbed ALL_TAGS=disco_f746ng generate_hello_world_mbed_project
$ cd tensorflow/lite/micro/tools/make/gen/mbed_cortex-m4_default/prj/hello_world/mbed
$ mbed config root .
$ mbed deploy
$ mbed compile -m DISCO_F746NG -t GCC_ARM
```

#### 將 make 後的 mbed.bin 上傳到 DISCO_F746NG 開發板

### (痛苦的 debug過程) DISCO_F746NG 執行 hello_world 當機
第一次執行時, 還來不及沒有打開 screen 接收 debug 訊息, 就一顆球在上方定住, 懷疑我的操作/操守有問題... 打開 screen, 出現 ** Error message **

```
x_value: 1.0*2^-127, y_value: 1.0*2^-127

x_value: 1.4361557*2^-4, y_value: 1.7621826*2^-4

x_value: 1.4361557*2^-3, y_value: 1.8977352*2^-3

x_value: 1.0771168*2^-2, y_value: 1.389413*2^-2

x_value: 1.4361557*2^-2, y_value: 1.5588537*2^-2

x_value: 1.7951952*2^-2, y_value: 1.7960706*2^-2

x_value: 1.0771168*2^-1, y_value: 1.965511*2^-2

x_value: 1.2566366*2^-1, y_value: 1.1183078*2^-1

x_value: 1.4361557*2^-1, y_value: 1.3724688*2^-1

x_value: 1.6156756*2^-1, y_value: 1.4910772*2^-1

x_value: 1.7951952*2^-1, y_value: 1.6605182*2^-1

x_value: 1.9747147*2^-1, y_value: 1.7791265*2^-1

x_value: 1.0771168*2^0, y_value: 1.7791265*2^-1

x_value: 1.1668766*2^0, y_value: 1.8977352*2^-1

x_value: 1.2566366*2^0, y_value: 1.9316229*2^-1

x_value: 1.3463962*2^0, y_value: 1.965511*2^-1

x_value: 1.4361557*2^0, y_value: 1.0166438*2^0

++ MbedOS Fault Handler ++

FaultType: HardFault

Context:
R0: 7C
R1: 8
R2: FFDB4437
R3: 1
R4: 20002D58
R5: 34
R6: A
R7: FFDB4437
R8: 0
R9: 72
R10: 8
R11: 68
R12: 34
SP   : 2004FF8C
LR   : 800051B
PC   : 8000472
xPSR : 1000200
PSP  : 0
MSP  : 2004FF20
CPUID: 410FC271
HFSR : 40000000
MMFSR: 0
BFSR : 4
UFSR : 0
DFSR : 9
AFSR : 0
Mode : Thread
Priv : Privileged
Stack: MSP

-- MbedOS Fault Handler --



++ MbedOS Error Info ++
Error Status: 0x80FF013D Code: 317 Module: 255
Error Message: Fault exception
Location: 0x8000472
Error Value: 0x20002E34
For more info, visit: https://mbed.com/s/error?error=0x80FF013D&tgt=DISCO_F746NG
-- MbedOS Error Info --

```

查看 https://mbed.com/s/error?error=0x80FF013D&tgt=DISCO_F746NG 輸入錯誤碼 (error code) 0x80FF013D 後會產生以下訊息

```

Error Decoder
0x80FF013D
Type:
System
Module
Unknown module
Error Code
HardFault exception
Cortex-M HardFault exception has occurred. Please see https://os.mbed.com/docs/latest/tutorials/analyzing-mbed-os-crash-dump.html for more info.

```

進一步查看 https://os.mbed.com/docs/latest/tutorials/analyzing-mbed-os-crash-dump.html


```
The following Cortex-M fault exceptions trigger the Mbed OS fault exception handler.

    MemManage Exception - Memory accesses that violate the setup in the MPU and certain illegal memory accesses trigger memory management faults.
    BusFault Exception - When an error response is received during a transfer on the AHB interfaces, it produces bus faults.
    UsageFault Exception - Division by zero, unaligned accesses and trying to execute coprocessor instructions can cause usage faults.
    HardFault Exception - Triggered on all fault conditions or if the corresponding fault handler (one of the above) is not enabled.

```
猜可能是記憶體問題, 再看一下螢幕當機時, 球是在螢幕的最上方, 是否是超過螢幕的範圍而造成錯誤, 看一下原始檔案 output_handler.cc 跟 error message 可能是有衝突的.


```
# error message
x_value: 1.4361557*2^0, y_value: 1.0166438*2^0

# output_handler.cc
    y_pos = dot_radius + static_cast<int>(midpoint * (1.f - y_value));     # 原始程式會有問題

    y_pos = dot_radius + static_cast<int>(midpoint * (1.1f - y_value));    # 小調整後即可正常運作

```

<a id="arduino_nano33_hello_world"></a>  

## 在 Arduino Nano 33 BLE 上實現 hello_world {#arduino-nano33-hello-world}

在 §\@ref(arduinoide) Arduino IDE 安裝後, 將 Arduino Nano 33 BLE 接上電腦的 USB, 進入 Arduino IDE 的 Tools - Boards 及 Port 確定已經安裝完成, 再到 File - Examples 找到 Arduino_TensorFlowLite 下會有 4 個範例  

* hello_world  
* magic_wand  
* micro_speech  
* person_detection  

選擇我們想要的範例 hello_world 執行即可.

執行中, 可以打開 Arduino IDE menu   
* Tool - Serial Monitor : 看到 Nano 33 回饋的預測 X、Y 值 
* Tool - Serial Plotter : 看到 Nano 33 回饋的預測 X、Y 值展開的圖形

同時, Nano 33 的燈號也會隨著辨識結果, 逐漸變亮到熄滅再變亮

## 在 ESP32-CAM 上實現 hello_world {#esp32-cam-hello-world}

這裡不說明 Arduino 的作法(作法更 Arduino Nano 33 大同小異), 僅就 esp-idf 方法做說明  

在 §\@ref(esp-idf) esp-idf 安裝且測試完 ESP32 的 hello world 後, 現在測試的是 TensorFlow Lite Micro 的 hello_world. 類似 STM32 DISCO_F746NG 的 Makefile 的作法

在 idf.py build 這步驟出現錯誤  

```
$ git clone https://github.com/tensorflow/tensorflow.git
$ cd tensorflow
$ make -f tensorflow/lite/micro/tools/make/Makefile TARGET=esp generate_hello_world_esp_project
$ cd tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf
$ idf.py build

-- Configuring done
CMake Error at /home/rafael/esp/esp-idf/tools/cmake/project.cmake:461 (target_link_libraries):
Error evaluating generator expression:

$<IN_LIST:-DTF_LITE_STATIC_MEMORY,$<TARGET_PROPERTY:__idf_tfmicro,COMPILE_OPTIONS>>
Expression did not evaluate to a known generator expression
Call Stack (most recent call first):
CMakeLists.txt:3 (project)

CMake Error in main/CMakeLists.txt:
Error evaluating generator expression:

$<IN_LIST:-DTF_LITE_STATIC_MEMORY,$<TARGET_PROPERTY:__idf_tfmicro,COMPILE_OPTIONS>>
Expression did not evaluate to a known generator expression

-- Generating done
-- Build files have been written to: /home/rafael/tensorflow/tensorflow/lite/micro/tools/make/gen/esp_xtensa-esp32/prj/hello_world/esp-idf/build
cmake failed with exit code 1
```

Google 後發現 [ESP32 Hello World project crashing in the target](https://github.com/tensorflow/tensorflow/issues/42165#issuecomment-751882110) 說明 cmake 的 compile option 需要 3.11 版本以上, 查了我的 cmake 版本是 3.10.2, 所以需要升級  

```
$ cmake --version
cmake version 3.10.2
```

[cmake 升級作法](https://askubuntu.com/questions/829310/how-to-upgrade-cmake-in-ubuntu)

```
# 從 https://cmake.org/download/ 下載 tar file, 到下載 tar file 的目錄下執行:

$ cd $CMAKE_DOWNLOAD_PATH
$ ./configure
$ make
$ sudo make install
```

再執行 idf, 可以結束從開發板傳回來的 X 跟 Y 的值  

```
$ idf.py build
$ idf.py -p PORT flash monitor 
```

提醒 : 執行 monitor 程式時, 如果要離開, 需要按 ‘Ctrl’ + ‘]’ 的組合鍵.
