`r if (knitr::is_html_output()) '
# References 參考文獻  {-}
'`

本書是基於 [TinyML TensorFLow Lite 機器學習中文版](https://www.books.com.tw/products/0010865580) 內容的實驗結果, 作者 Pete Warden 及 Daniel Situnayake 均於 Google 工作. 可以參考 Pete 相關論文、影片如下.   

關於 Make 及 Makefile  
1. [取消 TAGS 程式不受影響](https://github.com/tensorflow/tensorflow/issues/46667#issuecomment-766923481)  
2. [STM32F 選用 OPTIMIZED_KERNEL_DIR=cmsis_nn 來做最佳化](https://github.com/tensorflow/tensorflow/issues/46667#issuecomment-766927681)  

英文參考文章 mbed / arm / STM  
3. [mbed-cli v6.7 installation](https://os.mbed.com/docs/mbed-os/v6.7/build-tools/install-and-set-up.html)  
4. [mbed-cli v5.15 manual installation](https://os.mbed.com/docs/mbed-os/v5.15/tools/manual-installation.html)  
5. [Build Arm Cortex-M voice assistant with Google TensorFlow Lite](https://developer.arm.com/solutions/machine-learning-on-arm/developer-material/how-to-guides/build-arm-cortex-m-voice-assistant-with-google-tensorflow-lite/single-page)  
6. [CMSIS - Cortex Microcontroller Software Interface Standard](http://www.longlandclan.yi.org/~stuartl/stm32f10x_stdperiph_lib_um/CMSIS_Core.htm)  
7. [STM32F10x Standard Peripherals Library Peripheral’s Drivers Description](http://www.longlandclan.yi.org/~stuartl/stm32f10x_stdperiph_lib_um/Library_Files.html#_cmsis)  
8. [what means about “-DSTM32F10X_MD -DUSE_STDPERIPH_DRIVER” as the flags of arm-none-eabi-gcc?](https://stackoverflow.com/questions/59053389/what-means-about-dstm32f10x-md-duse-stdperiph-driver-as-the-flags-of-arm-non)

Arduino 相關  
9. [USB 無法偵測到 Arduino Nano BLE 33](https://forum.arduino.cc/index.php?topic=659995.0) : 我一開始從 Mac 下載程式到 Nano 後, Nano 執行結果不如預期, 擔心是 Mac 的 USB 有問題(一直有遇到類似問題), 轉到 PC Windows 下, 發現 USB 偵測不到 Nano, 甚至懷疑到我 PC 的 USB driver 有問題, 結果是, 如果 Nano 下載的程式有問題, 是有可能造成 USB 偵測不到, 需要 reset Nano, 重新刷 firmware, 後 USB 才能正常偵測到 Nano.  

其它  
10. [Neural Network on Mobile (nnom) by Ma Jianjia - github](https://github.com/majianjia/nnom)  

TensorFlow  
11. [Tensorflow.org 官網](https://www.tensorflow.org/lite/guide)  
12. [TensorFlow for microcontroller - 官網](https://www.tensorflow.org/lite/microcontrollers)  
13. [Tensorflow Lite Micro on ESP32](https://blog.tensorflow.org/2020/08/announcing-tensorflow-lite-micro-esp32.html)  
14. [TensorFlow for Micro Github 官網 open source](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro)  
15. [TensorFlow Lite for Microcontroller Hello world examples](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/hello_world/README.md)  

TinyML (TensorFlow Lite Micro 一開始使用的名稱)  
16. [書 "TinyML Tensor Flow Lite 機器學習“ 英文版 O'Reilly 出版](https://www.oreilly.com/library/view/tinyml/9781492052036/)  
17. [書 "TinyML Tensor Flow Lite 機器學習“ 中文版 O'Reilly 出版](https://www.books.com.tw/products/0010865580?fbclid=IwAR1xgb-0LStRrHXajKT-u3uP982d0p8PQaDpNfhxHAzuCbATi6VOjYcwo2k)   
18. [pdf - TinyML_Machine_Learning_with_TensorFlow_Lite_on_Arduino_and_Ultra.pdf](http://lib.samtuit.uz/admin/kitoblar/5f8eb590b69fb5.80592706TinyML_Machine_Learning_with_TensorFlow_Lite_on_Arduino_and_Ultra.pdf)  

Pete Warden 及相關資料  
19. [Pete Warden's blog](https://petewarden.com/?s=tinyml&submit=Search)  
20. [Paper - TensorFlow Lite Micro](https://arxiv.org/pdf/2010.08678.pdf)  
21. [Pete youtube TinyML book #1 chap 4 - hello world training model](https://www.youtube.com/watch?v=8N6-WQsxwxA)  
22. [Pete youtube TinyML book #2 chap 5/6 - Deploying the Hello World model on an Arduino](https://www.youtube.com/watch?v=AfAyHheBk6Y)  
23. [Pete youtube TinyML book #3 - Introduction to TensorFlow Lite for Microcontrollers](https://www.youtube.com/watch?v=_NcG5estXOU)  
24. [Pete youtube TinyML book #4 - Quantization](https://www.youtube.com/watch?v=-jBmqY_aFwE)  
25. [Pete youtube What's TinyML good for \@ AIoT Dev Summit keynote](https://www.youtube.com/watch?v=Wuq2aP5O5Z0)  
26. [Getting Started with TinyML - Pete Warden - TinyML.org - March 31, 2020](https://forums.tinyml.org/t/getting-started-with-tinyml-pete-warden-march-31-2020/22)  
27. [Getting Started with TinyML - Pete Warden - TinyML.org - March 31, 2020 - youtube](https://www.youtube.com/watch?v=soOM1F70Boc)  
28. [Getting Started with TinyML - Pete Warden - TinyML.org - March 31, 2020 - slides](https://cms.tinyml.org/wp-content/uploads/talks2020/tinyML_Talks_200331_Pete_Warden.pdf)  
29. [Pete Warden, Staff Research Engineer and TensorFlow Lite development lead at Google, presents the "Using TensorFlow Lite to Deploy Deep Learning on Cortex-M Microcontrollers" tutorial at the May 2019 Embedded Vision Summit](https://www.edge-ai-vision.com/2019/06/using-tensorflow-lite-to-deploy-deep-learning-on-cortex-m-microcontrollers-a-presentation-from-google/)  
30. [Introducing the SparkFun Edge - Tiny models on tiny computers!](https://www.hackster.io/news/introducing-the-sparkfun-edge-34c9eb80a000)  

關於 TinyML 的另一位作者, 已經離開 Google 的 Daniel Situnayake   
31. [Daniel Situnayake's blog](https://situnayake.com)